// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aepjkwkaikdnsorlrmqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlcGprd2thaWtkbnNvcmxybXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODQxODgsImV4cCI6MjA2MTQ2MDE4OH0.e9MP4_ec853-vZMwnWOvmJ9SvGjrZxgDQSlNcMno_x0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);